database:
  #  mysql
  #  url: jdbc:mysql://122.44.88.239:33069/msaportal
  #  mssql
  # url: jdbc:sqlserver://122.44.88.239:1433
  # url: jdbc:sqlserver://211.57.200.99
  # url: jdbc:sqlserver://hs.medieng.com
    url: jdbc:sqlserver://food.medieng.com
    
spring:
  datasource:
    #    url: ${database.url}?serverTimezone=Asia/Seoul&autoReconnect=true&validationQuery=select 1
    #    username: msaportal
    #    password: msaportal8595
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${database.url};DatabaseName=msaportal;encrypt=false;
    username: FoodPlan
    password: FoodPlan
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mail: # 비밀번호 변경 이메일 발송
    host: smtp.gmail.com # smtp host
    port: 587 # smtp port
    username: email_username # 계정
    password: 'email_password' # 비밀번호 - 구글 보안 2단계 인증 해제, 보안 수준이 낮은 앱의 액세스 허용(https://myaccount.google.com/lesssecureapps)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
